Repository vaadin/vaadin-grid, pull requests merged in 2018-09, with the labels that each got.

#1387 Feature/convenience properties
  src/vaadin-grid-a11y-mixin.html
  src/vaadin-grid-column.html
  test/accessibility.html
  test/column-group.html
  test/column-groups.html
  test/column.html
Labels: in review

#1390 Fix bad merging in commit fbe74fc2e
  demo/grid-filtering-demos.html
Labels: in review

#1392 Add render method for manual triggering renderers
  src/vaadin-grid-column.html
  src/vaadin-grid.html
  test/renderers.html
Labels: in review

#1399 Add convenience vaadin-grid-sort-column helper element
  bower.json
  demo/grid-sorting-demos.html
  src/all-imports.html
  src/vaadin-grid-column.html
  src/vaadin-grid-sort-column.html
  test/sorting.html
  theme/lumo/all-imports.html
  theme/lumo/vaadin-grid-sort-column.html
  theme/material/all-imports.html
  theme/material/vaadin-grid-sort-column.html
  vaadin-grid-sort-column.html
Labels: in review

#1393 Clean up row details rendering
  src/vaadin-grid-row-details-mixin.html
  src/vaadin-grid.html
  test/renderers.html
  test/row-details.html
  test/visual/screens/vaadin-grid/row-details-lumo/row-details-visible/chrome.png
Labels: in review

#1403 Revert "Add convenience vaadin-grid-sort-column helper element"
  bower.json
  demo/grid-sorting-demos.html
  src/all-imports.html
  src/vaadin-grid-column.html
  src/vaadin-grid-sort-column.html
  test/sorting.html
  theme/lumo/all-imports.html
  theme/lumo/vaadin-grid-sort-column.html
  theme/material/all-imports.html
  theme/material/vaadin-grid-sort-column.html
  vaadin-grid-sort-column.html
Labels: in review

#1400 Prefer column convenience properties in the demos [skip ci]
  README.md
  analysis.json
  demo/grid-basic-demos.html
  demo/grid-columns-demos.html
  demo/grid-data-demos.html
  demo/grid-demo-data.js
  demo/grid-filtering-demos.html
  demo/grid-pagination-demos.html
  demo/grid-row-details-demos.html
  demo/grid-selection-demos.html
  demo/grid-sorting-demos.html
  demo/grid-theme-demos.html
  demo/grid-tree-demos.html
  demo/index.html
  demo/x-data-provider.html
  src/vaadin-grid-column.html
  src/vaadin-grid.html
Labels: in review

#1397 Fix sorting other than last column
  src/vaadin-grid-sort-mixin.html
  test/sorting.html
Labels: in review unscoped

#1409 fix: linter errors in demos
  demo/grid-row-details-demos.html
  demo/grid-selection-demos.html
Labels: in review

#1410 Fix visual tests
  test/visual/column-groups.html
  test/visual/header-footer.html
  test/visual/row-details.html
  test/visual/screens/vaadin-grid/column-groups-lumo/column-groups/chrome.png
  test/visual/screens/vaadin-grid/column-groups-material/column-groups/chrome.png
  test/visual/screens/vaadin-grid/row-details-lumo/row-details-initial/chrome.png
  test/visual/screens/vaadin-grid/row-details-lumo/row-details-visible/chrome.png
  test/visual/screens/vaadin-grid/row-details-material/row-details-initial/chrome.png
  test/visual/screens/vaadin-grid/row-details-material/row-details-visible/chrome.png
  test/visual/screens/vaadin-grid/sorting-lumo/multiple-columns-asc-asc/chrome.png
  test/visual/screens/vaadin-grid/sorting-lumo/multiple-columns-asc-desc/chrome.png
  test/visual/screens/vaadin-grid/sorting-lumo/single-column-asc/chrome.png
  test/visual/screens/vaadin-grid/sorting-lumo/single-column-desc/chrome.png
  test/visual/screens/vaadin-grid/sorting-lumo/sorting-initial/chrome.png
  test/visual/screens/vaadin-grid/sorting-material/multiple-columns-asc-asc/chrome.png
  test/visual/screens/vaadin-grid/sorting-material/multiple-columns-asc-desc/chrome.png
  test/visual/screens/vaadin-grid/sorting-material/single-column-asc/chrome.png
  test/visual/screens/vaadin-grid/sorting-material/single-column-desc/chrome.png
  test/visual/screens/vaadin-grid/sorting-material/sorting-initial/chrome.png
  test/visual/sorting.html
Labels: in review

#1413 Unhide the header row if a label is defined for a column
  src/vaadin-grid-column.html
  test/column.html
Labels: in review

#1408 Restore the theme variant demo sorters
  demo/grid-theme-demos.html
Labels: in review unscoped

#1398 Sex max-width to vaadin-grid-filter
  demo/grid-filtering-demos.html
  src/vaadin-grid-filter.html
  test/filtering.html
Labels: in review unscoped

#1426 Rename model to rowData in the renderer docs and demos [skip ci]
  README.md
  demo/grid-basic-demos.html
  demo/grid-columns-demos.html
  demo/grid-crud-demos.html
  demo/grid-row-details-demos.html
  demo/grid-selection-demos.html
  demo/grid-tree-demos.html
  src/vaadin-grid-column.html
  src/vaadin-grid-row-details-mixin.html
  src/vaadin-grid.html
Labels: in review

#1427 Rename column label to header as more self-descriptive
  README.md
  demo/grid-basic-demos.html
  demo/grid-columns-demos.html
  demo/grid-crud-demos.html
  demo/grid-data-demos.html
  demo/grid-filtering-demos.html
  demo/grid-pagination-demos.html
  demo/grid-row-details-demos.html
  demo/grid-selection-demos.html
  demo/grid-theme-demos.html
  src/vaadin-grid-a11y-mixin.html
  src/vaadin-grid-column.html
  src/vaadin-grid.html
  test/accessibility.html
  test/column-groups.html
  test/column.html
Labels: in review

#1429 Fix text replacement
  src/vaadin-grid-column.html
  test/column.html
Labels: in review

#1421 Optimize increase pool
  src/vaadin-grid-column.html
  src/vaadin-grid-dynamic-columns-mixin.html
  src/vaadin-grid-row-details-mixin.html
  src/vaadin-grid-scroller.html
  src/vaadin-grid.html
  test/column-reordering.html
  test/column.html
  test/light-dom-observing.html
  test/physical-count.html
  test/row-details.html
  test/visual/screens/vaadin-grid/row-details-lumo/row-details-visible/chrome.png
Labels: in review

#1428 Use a complete row data model with new cells and renderers
  src/vaadin-grid-column.html
  src/vaadin-grid.html
  test/renderers.html
Labels: in review

#1430 Warn about invalid textAlign
  src/vaadin-grid-column.html
  test/column.html
Labels: in progress

#1432 Improve renderers docs [skip ci]
  demo/grid-basic-demos.html
  src/vaadin-grid-column.html
  src/vaadin-grid-row-details-mixin.html
  src/vaadin-grid.html
Labels: in progress

#1436 Add convenience vaadin-grid-filter-column helper element
  bower.json
  demo/grid-filtering-demos.html
  demo/index.html
  src/all-imports.html
  src/vaadin-grid-column.html
  src/vaadin-grid-filter-column.html
  test/filtering.html
  theme/lumo/all-imports.html
  theme/lumo/vaadin-grid-filter-column.html
  theme/material/all-imports.html
  theme/material/vaadin-grid-filter-column.html
  vaadin-grid-filter-column.html
Labels: in progress

#1440 Add convenience vaadin-grid-tree-column helper element
  bower.json
  demo/grid-sorting-demos.html
  demo/grid-tree-demos.html
  demo/index.html
  src/all-imports.html
  src/vaadin-grid-tree-column.html
  test/tree-toggle.html
  theme/lumo/all-imports.html
  theme/lumo/vaadin-grid-tree-column.html
  theme/material/all-imports.html
  theme/material/vaadin-grid-tree-column.html
  vaadin-grid-tree-column.html
Labels: in progress

#1441 Expanded, level and selected props in the renderer model API doc [skip ci]
  demo/grid-selection-demos.html
  src/vaadin-grid-column.html
Labels: in progress

#1443 Update selection demo to not use Polymer [skip ci]
  demo/grid-selection-demos.html
Labels: in progress

#1444 Add `first-column` attribute on the first visible column
  src/vaadin-grid-column-reordering-mixin.html
  src/vaadin-grid-dynamic-columns-mixin.html
  src/vaadin-grid.html
  test/column-reordering.html
Labels: in progress

#1445 Cleanup demos, fix pagination demo [skip ci]
  demo/grid-pagination-demos.html
  demo/grid-theme-demos.html
  demo/grid-tree-demos.html
Labels: in progress
