Repository vaadin/vaadin-grid, pull requests merged in 2019-04, with the labels that each got.

#1588 fix: Force reflow on column width change
  src/vaadin-grid-column.html
  src/vaadin-grid.html
  test/frozen-columns.html
  test/helpers.html
  test/resizing.html
Labels: in progress

#1592 Add row drag and drop feature
  demo/demos.json
  demo/grid-drag-and-drop-demos.html
  demo/index.html
  src/vaadin-grid-drag-and-drop-mixin.html
  src/vaadin-grid.html
  test/drag-and-drop.html
  test/test-suites.js
  theme/lumo/vaadin-grid-styles.html
Labels: in progress

#1595 feat: column auto-width
  demo/grid-columns-demos.html
  src/vaadin-grid-column.html
  src/vaadin-grid-data-provider-mixin.html
  src/vaadin-grid.html
  test/.eslintrc.json
  test/column-auto-width.html
  test/helpers.html
  test/test-suites.js
Labels: in progress

#1596 Add Lumo and Material themes
  src/vaadin-grid-drag-and-drop-mixin.html
  src/vaadin-grid.html
  test/drag-and-drop.html
  test/visual/drag-and-drop.html
  test/visual/screens/vaadin-grid/drag-and-drop-lumo/grid-dragover/chrome.png
  test/visual/screens/vaadin-grid/drag-and-drop-lumo/row-dragover-above/chrome.png
  test/visual/screens/vaadin-grid/drag-and-drop-lumo/row-dragover-below/chrome.png
  test/visual/screens/vaadin-grid/drag-and-drop-lumo/row-dragover-on-top/chrome.png
  test/visual/screens/vaadin-grid/drag-and-drop-lumo/row-dragstart/chrome.png
  test/visual/screens/vaadin-grid/drag-and-drop-material/grid-dragover/chrome.png
  test/visual/screens/vaadin-grid/drag-and-drop-material/row-dragover-above/chrome.png
  test/visual/screens/vaadin-grid/drag-and-drop-material/row-dragover-below/chrome.png
  test/visual/screens/vaadin-grid/drag-and-drop-material/row-dragover-on-top/chrome.png
  test/visual/screens/vaadin-grid/drag-and-drop-material/row-dragstart/chrome.png
  test/visual/test.js
  theme/lumo/vaadin-grid-styles.html
  theme/material/vaadin-grid-styles.html
Labels: in progress

#1585 Add comments to the grid themes demo
  demo/grid-theme-demos.html
Labels: in review unscoped

#1604 Use animation frame timing in scroller for pool increase
  src/vaadin-grid-scroller.html
Labels: in progress

#1605 Use animation frame timing in scroller for pool increase
  src/vaadin-grid-scroller.html
Labels: in review

#1612 Add setDragData function to drag start event
  demo/grid-drag-and-drop-demos.html
  src/vaadin-grid-drag-and-drop-mixin.html
  test/drag-and-drop.html
Labels: in progress

#1613 Only include draggable rows in the viewport to the drag operation
  demo/grid-drag-and-drop-demos.html
  src/vaadin-grid-drag-and-drop-mixin.html
  test/drag-and-drop.html
Labels: in progress

#1614 Mobile polyfill adjustments
  src/vaadin-grid-drag-and-drop-mixin.html
  test/drag-and-drop.html
  theme/lumo/vaadin-grid-styles.html
  theme/material/vaadin-grid-styles.html
Labels: in review

#1615 Dnd cleanup and finishing touches
  demo/grid-drag-and-drop-demos.html
  src/vaadin-grid-drag-and-drop-mixin.html
  test/drag-and-drop.html
Labels: in progress
